# Generated by Django 3.2.11 on 2022-04-04 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Others', 'Others')], default=('Others', 'Others'), max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('passport', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('otherName', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Others', 'Others')], default=('Others', 'Others'), max_length=100)),
                ('maritalstatus', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorce', 'Divorce'), ('Widowed', 'Widowed'), ('Others', 'Others')], default=('Others', 'Others'), max_length=100)),
                ('maidenName', models.CharField(blank=True, max_length=100, null=True)),
                ('dateOfBirth', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('homeTelephone', models.CharField(blank=True, max_length=100, null=True)),
                ('customerHomeAddress', models.CharField(blank=True, max_length=1000, null=True)),
                ('heard_about_us', models.CharField(choices=[('Radio Station', 'Radio Station'), ('Magazine', 'Magazine'), ('Newspaper', 'Newspaper'), ('Facebook', 'Facebook'), ('Website', 'Website'), ('A friend', 'A friend'), ('Somewhere Online', 'Somewhere Online')], default=('Somewhere Online', 'Somewhere Online'), max_length=100)),
                ('nk_fullName', models.CharField(blank=True, max_length=100, null=True)),
                ('nk_telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('nk_email', models.CharField(blank=True, max_length=100, null=True)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('em_designation', models.CharField(blank=True, max_length=100, null=True)),
                ('em_telephone', models.CharField(blank=True, max_length=100, null=True)),
                ('em_address', models.CharField(blank=True, max_length=100, null=True)),
                ('dateRegistered', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Rubies Court 1', 'Rubies Court 1'), ('Rubies Court 2', 'Rubies Court 2'), ('Crystal Park', 'Crystal Park'), ('Mercy Gardens', 'Mercy Gardens'), ('Royal Park', 'Royal Park'), ('Oasis Gardens', 'Oasis Gardens')], max_length=100, null=True)),
                ('price', models.FloatField(max_length=100, null=True)),
                ('location', models.CharField(max_length=500, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.customer')),
                ('propertypurchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.property')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentplan', models.CharField(choices=[('outright', 'outright'), ('3 month instalment', '3 month instalment'), ('6 month instalment', '6 month instalment'), ('9 month instalment', '9 month instalment'), ('12 month instalment', '12 month instalment')], max_length=100, null=True)),
                ('initialpayment', models.IntegerField(null=True)),
                ('depositpayment', models.IntegerField(null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customerpayment', to='dashboard.purchase')),
            ],
        ),
    ]
