# Generated by Django 3.2.11 on 2022-04-08 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_property_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='dateRegistered',
            new_name='date_Registered',
        ),
    ]
