# Generated by Django 3.2.11 on 2022-04-08 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_rename_dateregistered_customer_date_registered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='date_Registered',
            new_name='dateRegistered',
        ),
    ]
