# Generated by Django 3.2.11 on 2022-04-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_date_registered_customer_dateregistered'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='heard_about_us2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
