# Generated by Django 3.2.11 on 2022-04-08 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customer_heard_about_us2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='initialpayment',
            new_name='Actual_payment',
        ),
    ]
