# Generated by Django 3.2.11 on 2022-04-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20220411_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='depositpayment',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='actual_payment',
            field=models.IntegerField(default='0', null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
