# Generated by Django 3.2.11 on 2022-04-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20220412_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='depositpayment',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentplan',
            field=models.CharField(choices=[('outright', 'outright'), ('3 month installment', '3 month installment'), ('6 month installment', '6 month installment'), ('9 month installment', '9 month installment'), ('12 month installment', '12 month instalment')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
