# Generated by Django 3.2.11 on 2022-04-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20220417_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=100),
        ),
    ]
