# Generated by Django 3.2.11 on 2022-04-17 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_payment_paymentmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='heard_about_us2',
            new_name='heard_about_person',
        ),
    ]
